name: palstore_welcome_page
description: MrDev ,Inc.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.0.0
  url_launcher: ^6.2.5
  lottie: ^2.7.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/img.png"


flutter:


  uses-material-design: true
  assets:
    - assets/images/
